extensions:
  # This extension is required for app management. Do not remove.
  commerce/extensibility/1:
    $include: src/commerce-extensibility-1/ext.config.yaml

productDependencies:
  - code: COMMC
    minVersion: 2.4.4
    maxVersion: 2.4.9
