const HTTP_OK = 200;
const HTTP_BAD_REQUEST = 400;
const HTTP_UNAUTHORIZED = 401;
const HTTP_NOT_FOUND = 404;
const HTTP_INTERNAL_ERROR = 500;
const BACKOFFICE_PROVIDER_KEY = "backoffice";
const PUBLISH_EVENT_SUCCESS = "OK";

export {
  BACKOFFICE_PROVIDER_KEY,
  HTTP_BAD_REQUEST,
  HTTP_INTERNAL_ERROR,
  HTTP_NOT_FOUND,
  HTTP_OK,
  HTTP_UNAUTHORIZED,
  PUBLISH_EVENT_SUCCESS,
};
