upsert:
  function: upsert/index.js
  web: 'no'
  runtime: nodejs:24
  inputs:
    LOG_LEVEL: $LOG_LEVEL
  annotations:
    final: true
created:
  function: created/index.js
  web: 'no'
  runtime: nodejs:24
  inputs:
    LOG_LEVEL: $LOG_LEVEL
  annotations:
    final: true
updated:
  function: updated/index.js
  web: 'no'
  runtime: nodejs:24
  inputs:
    LOG_LEVEL: $LOG_LEVEL
  annotations:
    final: true
