// This file has been auto-generated by `@adobe/aio-commerce-lib-app`
// Do not modify this file directly

import appConfig from "./app.commerce.manifest.json" with { type: "json" };

export default appConfig;
