// This file has been auto-generated by `@adobe/aio-commerce-lib-app`
// Do not modify this file directly

import { appConfigRuntimeAction } from "@adobe/aio-commerce-lib-app/actions/app-config";

import appConfig from "#app.commerce.config";

const args = { appConfig };
export const main = appConfigRuntimeAction(args);
