// This file has been auto-generated by `@adobe/aio-commerce-lib-app`
// Do not modify this file directly

import { associationRuntimeAction } from "@adobe/aio-commerce-lib-app/actions/association";

export const main = associationRuntimeAction();
