// This file has been auto-generated by `@adobe/aio-commerce-lib-app`
// Do not modify this file directly

import { installationRuntimeAction } from "@adobe/aio-commerce-lib-app/actions/installation"
import appConfig from "#app.commerce.config";

// No custom installation scripts configured
const args = { appConfig };
export const main = installationRuntimeAction(args);
